name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Create-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Create build
        run: |
          npm run build
